# Generated by Django 5.2.5 on 2025-09-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['disponible'], name='catalogo_bl_disponi_daa281_idx'), models.Index(fields=['orden'], name='catalogo_bl_orden_60d5ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='catalogo.bloque')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['bloque', 'disponible'], name='catalogo_ca_bloque__46d94e_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['padre'], name='catalogo_ca_padre_i_140bfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('bloque', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['disponible'], name='catalogo_pr_disponi_c81a90_idx'),
        ),
    ]
