# Generated by Django 5.2.5 on 2025-09-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.RemoveIndex(
            model_name='bloque',
            name='catalogo_bl_disponi_daa281_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='catalogo_ca_bloque__46d94e_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='catalogo_pr_disponi_c81a90_idx',
        ),
        migrations.RenameField(
            model_name='bloque',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='bloque',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='catalogo.bloque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='productos', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=160),
        ),
        migrations.AddIndex(
            model_name='bloque',
            index=models.Index(fields=['activo'], name='catalogo_bl_activo_3172f5_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['bloque', 'activo'], name='catalogo_ca_bloque__f9cf46_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='catalogo_pr_activo_05fd31_idx'),
        ),
    ]
